import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/app/provider'
import Header from '@/components/layouts/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'chatalk',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Provider>{children}</Provider>
      </body>
    </html>
  )
}
